name: 'Release'

permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Setup Variables'
        id: vars
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
          echo "PRERELEASE=`[[ ${GITHUB_REF#refs/*/v*-} == ${GITHUB_REF} ]] && echo 'false' || echo 'true'`" >> $GITHUB_ENV
          echo "CONFIGURATION=`[[ ${GITHUB_REF#refs/*/v*-} == ${GITHUB_REF} ]] && echo 'Release' || echo 'Debug'`" >> $GITHUB_ENV
        shell: bash
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: 'Restore .NET dependencies'
        run: dotnet restore --nologo
      - name: 'Run Tests'
        run: dotnet test --no-restore test/ViteIntegration.Tests/ViteIntegration.Tests.csproj
      - name: 'Build NuGet packages'
        run: |
          dotnet pack --no-restore --configuration ${{ env.CONFIGURATION }} -p:Version="${{ env.VERSION }}" -p:PackageVersion="${{ env.VERSION }}" src/ViteIntegration/ViteIntegration.csproj
      - name: 'Publish NuGet packages'
        run: |
          dotnet nuget push src/ViteIntegration/bin/${{ env.CONFIGURATION }}/ViteIntegration.${{ env.VERSION }}.nupkg -k ${{ secrets.NUGET_TOKEN }} -s "https://api.nuget.org/v3/index.json"
      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ env.PRERELEASE }}
          generate_release_notes: true
          files: |
            LICENSE
            src/ViteIntegration/bin/${{ env.CONFIGURATION }}/ViteIntegration.${{ env.VERSION }}.nupkg
